name: Main Branch Tag Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  say-hello:
    runs-on: self-hosted # Indique que ce job doit s'exécuter sur un runner auto-hébergé
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print Hello World
      run: echo "Hello World"